'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Bell, 
  AlertTriangle, 
  AlertCircle, 
  Info, 
  CheckCircle, 
  X,
  Clock,
  MapPin,
  ChevronRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Alert } from '@/lib/types'

// Demo alerts for visualization
const demoAlerts: Alert[] = [
  {
    id: '1',
    alertType: 'heatwave',
    severity: 'warning',
    title: 'Onda de Calor',
    description: 'Temperaturas acima de 35°C previstas para os próximos 3 dias',
    instructions: 'Mantenha-se hidratado e evite exposição ao sol entre 10h e 16h',
    active: true,
    autoGenerated: true,
    startsAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    alertType: 'fire',
    severity: 'watch',
    title: 'Risco de Incêndio',
    description: 'Condições favoráveis a incêndios florestais na região',
    active: true,
    autoGenerated: true,
    startsAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    alertType: 'rain',
    severity: 'advisory',
    title: 'Chuva Moderada',
    description: 'Pancadas de chuva previstas para esta tarde',
    active: true,
    autoGenerated: true,
    startsAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
]

function getSeverityConfig(severity: Alert['severity']) {
  switch (severity) {
    case 'emergency':
      return { 
        icon: AlertTriangle, 
        color: 'text-red-500', 
        bg: 'bg-red-500/10', 
        border: 'border-red-500/30',
        label: 'Emergência' 
      }
    case 'warning':
      return { 
        icon: AlertTriangle, 
        color: 'text-orange-500', 
        bg: 'bg-orange-500/10', 
        border: 'border-orange-500/30',
        label: 'Alerta' 
      }
    case 'watch':
      return { 
        icon: AlertCircle, 
        color: 'text-yellow-500', 
        bg: 'bg-yellow-500/10', 
        border: 'border-yellow-500/30',
        label: 'Atenção' 
      }
    case 'advisory':
      return { 
        icon: Info, 
        color: 'text-blue-500', 
        bg: 'bg-blue-500/10', 
        border: 'border-blue-500/30',
        label: 'Aviso' 
      }
    default:
      return { 
        icon: Info, 
        color: 'text-gray-500', 
        bg: 'bg-gray-500/10', 
        border: 'border-gray-500/30',
        label: 'Info' 
      }
  }
}

export default function AlertsPanel() {
  const [alerts, setAlerts] = useState<Alert[]>(demoAlerts)
  const [dismissedIds, setDismissedIds] = useState<Set<string>>(new Set())

  const activeAlerts = alerts.filter(a => a.active && !dismissedIds.has(a.id))

  const dismissAlert = (id: string) => {
    setDismissedIds(prev => new Set([...prev, id]))
  }

  return (
    <div className="rounded-xl border border-border bg-card p-6">
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Bell className="size-4 text-muted-foreground" />
          <h2 className="text-sm font-medium text-muted-foreground">Alertas Ativos</h2>
        </div>
        <span className={cn(
          'flex size-6 items-center justify-center rounded-full text-xs font-bold',
          activeAlerts.length > 0 
            ? 'bg-orange-500/20 text-orange-500' 
            : 'bg-green-500/20 text-green-500'
        )}>
          {activeAlerts.length}
        </span>
      </div>

      <AnimatePresence mode="popLayout">
        {activeAlerts.length > 0 ? (
          <div className="space-y-3">
            {activeAlerts.map((alert) => {
              const config = getSeverityConfig(alert.severity)
              const Icon = config.icon

              return (
                <motion.div
                  key={alert.id}
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className={cn(
                    'rounded-lg border p-4',
                    config.bg,
                    config.border
                  )}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex items-start gap-3">
                      <div className={cn('mt-0.5', config.color)}>
                        <Icon className="size-5" />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <span className={cn('text-xs font-medium uppercase', config.color)}>
                            {config.label}
                          </span>
                        </div>
                        <h3 className="mt-1 font-medium text-foreground">{alert.title}</h3>
                        <p className="mt-1 text-sm text-muted-foreground">{alert.description}</p>
                        
                        {alert.instructions && (
                          <div className="mt-2 rounded-md bg-background/50 p-2 text-xs text-muted-foreground">
                            {alert.instructions}
                          </div>
                        )}

                        <div className="mt-2 flex items-center gap-3 text-xs text-muted-foreground">
                          <div className="flex items-center gap-1">
                            <Clock className="size-3" />
                            {new Date(alert.createdAt).toLocaleTimeString('pt-BR', { 
                              hour: '2-digit', 
                              minute: '2-digit' 
                            })}
                          </div>
                        </div>
                      </div>
                    </div>
                    <button
                      onClick={() => dismissAlert(alert.id)}
                      className="rounded-lg p-1 text-muted-foreground transition-colors hover:bg-background/50 hover:text-foreground"
                    >
                      <X className="size-4" />
                    </button>
                  </div>
                </motion.div>
              )
            })}
          </div>
        ) : (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex flex-col items-center justify-center py-8 text-center"
          >
            <div className="flex size-12 items-center justify-center rounded-full bg-green-500/10">
              <CheckCircle className="size-6 text-green-500" />
            </div>
            <p className="mt-3 text-sm font-medium text-foreground">Tudo tranquilo</p>
            <p className="text-xs text-muted-foreground">Nenhum alerta ativo no momento</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
