// Weather data types
export interface WeatherData {
  temperature: number
  feelsLike: number
  humidity: number
  pressure: number
  windSpeed: number
  windDirection: number
  windGust?: number
  rain1h?: number
  uvIndex?: number
  visibility?: number
  cloudCover?: number
  dewPoint?: number
  weatherCode: number
  weatherDescription: string
  timestamp: string
}

export interface ForecastData {
  time: string
  temperatureMax: number
  temperatureMin: number
  temperature?: number
  humidity: number
  precipitationProbability: number
  precipitationSum: number
  windSpeed: number
  windDirection: number
  weatherCode: number
  uvIndex: number
}

export interface HourlyForecast {
  time: string
  temperature: number
  humidity: number
  precipitationProbability: number
  precipitation: number
  weatherCode: number
  windSpeed: number
  windDirection: number
}

// Air quality types
export interface AirQualityData {
  aqi: number
  aqiCategory: string
  pm25: number
  pm10: number
  co?: number
  no2?: number
  o3?: number
  so2?: number
  dominantPollutant: string
  timestamp: string
}

// Fire events
export interface FireEvent {
  id: string
  lat: number
  lng: number
  brightness: number
  confidence: 'low' | 'nominal' | 'high'
  confidencePct?: number
  frp: number
  satellite: string
  instrument: string
  detectedAt: string
  distance?: number
}

// Alerts
export interface Alert {
  id: string
  alertType: 'flood' | 'fire' | 'storm' | 'heatwave' | 'cold_wave' | 'air_quality' | 'wind' | 'rain' | 'drought' | 'custom'
  severity: 'info' | 'advisory' | 'watch' | 'warning' | 'emergency'
  title: string
  description: string
  instructions?: string
  lat?: number
  lng?: number
  radiusKm?: number
  active: boolean
  autoGenerated: boolean
  startsAt: string
  expiresAt?: string
  acknowledgedAt?: string
  acknowledgedBy?: string
  createdAt: string
}

// Station types
export interface Station {
  id: string
  organizationId: string
  stationCode: string
  name: string
  description?: string
  lat: number
  lng: number
  altitudeM?: number
  city: string
  state: string
  country: string
  stationType: 'virtual' | 'physical' | 'hybrid'
  status: 'active' | 'inactive' | 'maintenance' | 'offline'
  sensors: string[]
  lastDataAt?: string
  createdAt: string
}

// Risk analysis
export interface RiskAnalysis {
  id: string
  analysisType: 'flood' | 'fire' | 'storm' | 'heatwave' | 'composite' | 'anomaly'
  riskScore: number
  riskLevel: 'minimal' | 'low' | 'moderate' | 'high' | 'extreme'
  confidence: number
  factors: RiskFactor[]
  recommendations: string[]
  predictionWindowHours: number
  validUntil: string
  createdAt: string
}

export interface RiskFactor {
  name: string
  value: number
  weight: number
  contribution: number
  description: string
}

// Organization
export interface Organization {
  id: string
  name: string
  slug: string
  plan: 'free' | 'starter' | 'professional' | 'enterprise'
  logoUrl?: string
  primaryColor: string
  maxStations: number
  maxUsers: number
  isActive: boolean
  settings: Record<string, unknown>
  createdAt: string
}

// User profile
export interface Profile {
  id: string
  organizationId?: string
  email: string
  fullName: string
  avatarUrl?: string
  role: 'user' | 'operator' | 'manager' | 'admin' | 'super_admin'
  phone?: string
  jobTitle?: string
  preferences: UserPreferences
  lastLogin?: string
  isActive: boolean
  createdAt: string
}

export interface UserPreferences {
  theme: 'light' | 'dark' | 'system'
  notifications: boolean
  language: string
  temperatureUnit: 'celsius' | 'fahrenheit'
  defaultStationId?: string
}

// IoT types
export interface IoTDevice {
  id: string
  stationId: string
  deviceCode: string
  deviceType: 'esp32' | 'esp8266' | 'lora_node' | 'lora_gateway' | 'sensor_hub' | 'camera' | 'weather_station'
  name: string
  firmwareVersion?: string
  hardwareVersion?: string
  macAddress?: string
  ipAddress?: string
  lastSeen?: string
  lastTelemetry?: Record<string, unknown>
  status: 'online' | 'offline' | 'error' | 'maintenance'
  batteryLevel?: number
  signalStrength?: number
  config: Record<string, unknown>
  createdAt: string
}

// Radar data
export interface RadarFrame {
  time: number
  path: string
}

export interface RadarData {
  generated: number
  host: string
  radar: {
    past: RadarFrame[]
    nowcast: RadarFrame[]
  }
  satellite?: {
    infrared: RadarFrame[]
  }
}

// Dashboard metrics
export interface DashboardMetrics {
  totalStations: number
  activeStations: number
  offlineStations: number
  activeAlerts: number
  criticalAlerts: number
  fireEvents24h: number
  avgTemperature: number
  avgHumidity: number
  avgAqi: number
}

// API response types
export interface ApiResponse<T> {
  data: T
  error?: string
  timestamp: string
}
