'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Bell, 
  AlertTriangle, 
  AlertCircle, 
  Info, 
  CheckCircle,
  Filter,
  Search,
  Clock,
  MapPin,
  Flame,
  CloudRain,
  Thermometer,
  Wind,
  Eye,
  X,
  Check,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Alert } from '@/lib/types'

// Demo alerts data
const allAlerts: Alert[] = [
  {
    id: '1',
    alertType: 'heatwave',
    severity: 'warning',
    title: 'Onda de Calor Intensa',
    description: 'Temperaturas acima de 35°C previstas para os próximos 3 dias na região de São João da Boa Vista',
    instructions: 'Mantenha-se hidratado, evite exposição ao sol entre 10h e 16h, e monitore grupos de risco.',
    lat: -21.9694,
    lng: -46.7967,
    radiusKm: 50,
    active: true,
    autoGenerated: true,
    startsAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    alertType: 'fire',
    severity: 'watch',
    title: 'Risco Elevado de Incêndio',
    description: 'Condições meteorológicas favoráveis a incêndios florestais. Umidade relativa baixa e ventos fortes.',
    instructions: 'Evite queimadas, mantenha áreas limpas de material combustível.',
    active: true,
    autoGenerated: true,
    startsAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    alertType: 'rain',
    severity: 'advisory',
    title: 'Pancadas de Chuva Moderada',
    description: 'Previsão de pancadas de chuva isoladas com trovoadas para o período da tarde.',
    active: true,
    autoGenerated: true,
    startsAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    alertType: 'air_quality',
    severity: 'info',
    title: 'Qualidade do Ar Moderada',
    description: 'Índice AQI em 85. Pessoas sensíveis devem reduzir atividades ao ar livre prolongadas.',
    active: true,
    autoGenerated: true,
    startsAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    alertType: 'storm',
    severity: 'warning',
    title: 'Tempestade Prevista',
    description: 'Sistema de tempestade se aproximando da região. Ventos de até 60 km/h e granizo possível.',
    instructions: 'Evite áreas abertas, recolha objetos soltos e mantenha-se informado.',
    active: false,
    autoGenerated: true,
    acknowledgedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    acknowledgedBy: 'operador@sai.gov.br',
    startsAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]

const severityConfig = {
  emergency: { 
    icon: AlertTriangle, 
    color: 'text-red-500', 
    bg: 'bg-red-500/10', 
    border: 'border-red-500/30',
    label: 'Emergência' 
  },
  warning: { 
    icon: AlertTriangle, 
    color: 'text-orange-500', 
    bg: 'bg-orange-500/10', 
    border: 'border-orange-500/30',
    label: 'Alerta' 
  },
  watch: { 
    icon: AlertCircle, 
    color: 'text-yellow-500', 
    bg: 'bg-yellow-500/10', 
    border: 'border-yellow-500/30',
    label: 'Atenção' 
  },
  advisory: { 
    icon: Info, 
    color: 'text-blue-500', 
    bg: 'bg-blue-500/10', 
    border: 'border-blue-500/30',
    label: 'Aviso' 
  },
  info: { 
    icon: Info, 
    color: 'text-gray-500', 
    bg: 'bg-gray-500/10', 
    border: 'border-gray-500/30',
    label: 'Info' 
  },
}

const alertTypeIcons = {
  heatwave: Thermometer,
  fire: Flame,
  rain: CloudRain,
  storm: CloudRain,
  wind: Wind,
  air_quality: Eye,
  flood: CloudRain,
  cold_wave: Thermometer,
  drought: Thermometer,
  custom: Bell,
}

export default function AlertsPage() {
  const [alerts] = useState<Alert[]>(allAlerts)
  const [filter, setFilter] = useState<'all' | 'active' | 'resolved'>('all')
  const [searchTerm, setSearchTerm] = useState('')
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null)

  const filteredAlerts = alerts.filter((alert) => {
    if (filter === 'active' && !alert.active) return false
    if (filter === 'resolved' && alert.active) return false
    if (searchTerm && !alert.title.toLowerCase().includes(searchTerm.toLowerCase())) return false
    return true
  })

  const activeCount = alerts.filter(a => a.active).length
  const criticalCount = alerts.filter(a => a.active && (a.severity === 'emergency' || a.severity === 'warning')).length

  return (
    <div className="min-h-screen p-4 lg:p-6">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-foreground lg:text-3xl">Alertas</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Gerencie e monitore todos os alertas climáticos
        </p>
      </div>

      {/* Stats */}
      <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10">
              <Bell className="size-5 text-primary" />
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{alerts.length}</div>
              <div className="text-xs text-muted-foreground">Total</div>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-orange-500/10">
              <AlertCircle className="size-5 text-orange-500" />
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{activeCount}</div>
              <div className="text-xs text-muted-foreground">Ativos</div>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-red-500/10">
              <AlertTriangle className="size-5 text-red-500" />
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{criticalCount}</div>
              <div className="text-xs text-muted-foreground">Críticos</div>
            </div>
          </div>
        </div>
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-green-500/10">
              <CheckCircle className="size-5 text-green-500" />
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{alerts.length - activeCount}</div>
              <div className="text-xs text-muted-foreground">Resolvidos</div>
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex gap-2">
          {(['all', 'active', 'resolved'] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={cn(
                'rounded-lg px-4 py-2 text-sm font-medium transition-colors',
                filter === f
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-card text-muted-foreground hover:bg-secondary hover:text-foreground'
              )}
            >
              {f === 'all' ? 'Todos' : f === 'active' ? 'Ativos' : 'Resolvidos'}
            </button>
          ))}
        </div>
        <div className="relative">
          <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <input
            type="text"
            placeholder="Buscar alertas..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full rounded-lg border border-border bg-card py-2 pl-10 pr-4 text-sm text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary sm:w-64"
          />
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-4">
        <AnimatePresence mode="popLayout">
          {filteredAlerts.map((alert) => {
            const config = severityConfig[alert.severity]
            const SeverityIcon = config.icon
            const TypeIcon = alertTypeIcons[alert.alertType] || Bell

            return (
              <motion.div
                key={alert.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                layoutId={alert.id}
                onClick={() => setSelectedAlert(alert)}
                className={cn(
                  'cursor-pointer rounded-xl border p-4 transition-all hover:shadow-lg lg:p-6',
                  alert.active 
                    ? cn(config.bg, config.border)
                    : 'border-border bg-card opacity-75'
                )}
              >
                <div className="flex items-start gap-4">
                  <div className={cn(
                    'flex size-12 shrink-0 items-center justify-center rounded-lg',
                    alert.active ? config.bg : 'bg-secondary'
                  )}>
                    <TypeIcon className={cn('size-6', alert.active ? config.color : 'text-muted-foreground')} />
                  </div>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className={cn(
                        'inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium',
                        config.bg, config.color
                      )}>
                        <SeverityIcon className="size-3" />
                        {config.label}
                      </span>
                      {!alert.active && (
                        <span className="inline-flex items-center gap-1 rounded-full bg-green-500/10 px-2 py-0.5 text-xs font-medium text-green-500">
                          <Check className="size-3" />
                          Resolvido
                        </span>
                      )}
                    </div>

                    <h3 className="mt-2 text-lg font-semibold text-foreground">{alert.title}</h3>
                    <p className="mt-1 text-sm text-muted-foreground line-clamp-2">{alert.description}</p>

                    <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
                      <div className="flex items-center gap-1">
                        <Clock className="size-3" />
                        {new Date(alert.createdAt).toLocaleString('pt-BR', {
                          day: '2-digit',
                          month: '2-digit',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </div>
                      {alert.expiresAt && (
                        <div className="flex items-center gap-1">
                          <span>Expira:</span>
                          {new Date(alert.expiresAt).toLocaleString('pt-BR', {
                            day: '2-digit',
                            month: '2-digit',
                            hour: '2-digit',
                            minute: '2-digit',
                          })}
                        </div>
                      )}
                      {alert.acknowledgedBy && (
                        <div className="flex items-center gap-1">
                          <Check className="size-3" />
                          {alert.acknowledgedBy}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </motion.div>
            )
          })}
        </AnimatePresence>

        {filteredAlerts.length === 0 && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <div className="flex size-16 items-center justify-center rounded-full bg-secondary">
              <Bell className="size-8 text-muted-foreground" />
            </div>
            <p className="mt-4 text-lg font-medium text-foreground">Nenhum alerta encontrado</p>
            <p className="text-sm text-muted-foreground">
              {searchTerm ? 'Tente uma busca diferente' : 'Não há alertas no momento'}
            </p>
          </div>
        )}
      </div>

      {/* Alert Detail Modal */}
      <AnimatePresence>
        {selectedAlert && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm"
            onClick={() => setSelectedAlert(null)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={(e) => e.stopPropagation()}
              className="w-full max-w-lg rounded-xl border border-border bg-card p-6"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  {(() => {
                    const config = severityConfig[selectedAlert.severity]
                    const TypeIcon = alertTypeIcons[selectedAlert.alertType] || Bell
                    return (
                      <div className={cn('flex size-12 items-center justify-center rounded-lg', config.bg)}>
                        <TypeIcon className={cn('size-6', config.color)} />
                      </div>
                    )
                  })()}
                  <div>
                    <span className={cn(
                      'text-xs font-medium uppercase',
                      severityConfig[selectedAlert.severity].color
                    )}>
                      {severityConfig[selectedAlert.severity].label}
                    </span>
                    <h2 className="text-xl font-bold text-foreground">{selectedAlert.title}</h2>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedAlert(null)}
                  className="rounded-lg p-2 text-muted-foreground hover:bg-secondary hover:text-foreground"
                >
                  <X className="size-5" />
                </button>
              </div>

              <p className="mt-4 text-muted-foreground">{selectedAlert.description}</p>

              {selectedAlert.instructions && (
                <div className="mt-4 rounded-lg bg-secondary p-4">
                  <h4 className="text-sm font-medium text-foreground">Instruções</h4>
                  <p className="mt-1 text-sm text-muted-foreground">{selectedAlert.instructions}</p>
                </div>
              )}

              <div className="mt-6 flex gap-3">
                {selectedAlert.active && (
                  <button className="flex-1 rounded-lg bg-primary py-2 font-medium text-primary-foreground transition-colors hover:bg-primary/90">
                    Reconhecer Alerta
                  </button>
                )}
                <button
                  onClick={() => setSelectedAlert(null)}
                  className="flex-1 rounded-lg border border-border py-2 font-medium text-foreground transition-colors hover:bg-secondary"
                >
                  Fechar
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
